### ISSUE TITLE
属性与原生对应不上?

### ISSUE THREAD

**Issue by liuhongjian0316** [yangyanggu/amap-district-cluster#1]
renderOptions: {
  getClusterMarkerPosition: DistrictCluster.ClusterMarkerPositionStrategy.AVERAGE_POINTS_POSITION,
  getClusterMarker: Function
}
区域划分聚合，自定义显示标签

**Comment by yangyanggu** [comment]
不是百分百一样的

**Comment by liuhongjian0316** [comment]
好的了解 已经解决多谢
