### ISSUE TITLE
与官网的一些参数不符

### ISSUE THREAD

**Issue by liuhongjian0316** [yangyanggu/amap-district-cluster#2]
与官网的一些参数不符

**Comment by yangyanggu** [comment]
具体是哪些，肯定不会百分百匹配

**Comment by liuhongjian0316** [comment]
支持renderConstructor这个参数吗

**Comment by yangyanggu** [comment]
不支持，官方插件使用canvas实现，我直接用的内置对象，所以那个参数肯定不支持，需要的话可以用官方的插件

**Comment by liuhongjian0316** [comment]
那renderOptions中显示的内容我想动态切换 切换完如何重新渲染

**Comment by yangyanggu** [comment]
你想要的是更新渲染参数后强制重新渲染？

**Comment by liuhongjian0316** [comment]
renderOptions中的renderClusterMarker中自定义显示 里面根据不同的flag显示不同的内容  每次切换后 我想重新强制渲染

**Comment by yangyanggu** [comment]
可以，最近我加个强制刷新的方法吧

**Comment by liuhongjian0316** [comment]
刷新可以不挪动位置吗

**Comment by yangyanggu** [comment]
强制刷新的话肯定不会变位置，就是重新执行刷新，不走缓存，目前内部做了缓存处理，不移动地图的情况下执行render会直接走缓存导致不更新，加个强制刷新就是去掉缓存

**Comment by liuhongjian0316** [comment]
那行麻烦你添加下方法吧 多谢

**Comment by yangyanggu** [comment]
加好了，用最新的版本吧

**Comment by liuhongjian0316** [comment]
好的

**Comment by liuhongjian0316** [comment]
实例中没找到那个forceRender的方法

**Comment by yangyanggu** [comment]
看你的版本是不是0.0.8，我自己测试了有那个方法

**Comment by liuhongjian0316** [comment]
我看内部的版本对不上
![image](https://user-images.githubusercontent.com/45460278/236776902-ae968c43-ab6f-4ea8-927f-1a126604183b.png)

**Comment by yangyanggu** [comment]
等下我把组件库也升级下吧

**Comment by liuhongjian0316** [comment]
好的

**Comment by yangyanggu** [comment]
行了，组件库可以用最新的了

**Comment by liuhongjian0316** [comment]
The latest release of @vuemap/vue-amap is "2.0.9".

**Comment by yangyanggu** [comment]
直接指定2.0.10，还有别走cnpm之类的

**Comment by liuhongjian0316** [comment]
pnpm

**Comment by liuhongjian0316** [comment]
amapLayerDistrictClusterRef.value?.$$getInstance()和 amapLayerDistrictClusterRef.value中没有找到这个事件

**Comment by yangyanggu** [comment]
找不到事件是什么意思

**Comment by liuhongjian0316** [comment]
找不到这个forceRender  方法

**Comment by liuhongjian0316** [comment]
![image](https://user-images.githubusercontent.com/45460278/236806128-b265bafc-7fea-443c-9aa3-67506b7fda8a.png)

**Comment by liuhongjian0316** [comment]
![image](https://user-images.githubusercontent.com/45460278/236806224-6271fb34-6fea-4ff3-a7dd-0293e7eadfe2.png)

**Comment by yangyanggu** [comment]
确认下你现在里面那个插件的版本是不是0.0.8，是的话应该不会不存在方法，也可以把对象打印出来看看

**Comment by liuhongjian0316** [comment]
![image](https://user-images.githubusercontent.com/45460278/236807247-0ae02673-b05e-4c09-a88c-7c1bc3ee2600.png)
![image](https://user-images.githubusercontent.com/45460278/236807374-2796f353-a751-4f02-a9cd-9ce897a5f643.png)
![image](https://user-images.githubusercontent.com/45460278/236807395-b8f82c1a-87e2-47c3-a6e8-3a80924ac9d9.png)

**Comment by yangyanggu** [comment]
看最后一张图片sr里面的prototype里面的方法

**Comment by liuhongjian0316** [comment]
![image](https://user-images.githubusercontent.com/45460278/236808782-46b9ab77-697a-4c84-acf9-aaa1634d5ad8.png)

**Comment by yangyanggu** [comment]
这个对象不对，你现在生效的应该还是0.0.7的版本，你检查下缓存还有本地的node_modules

**Comment by liuhongjian0316** [comment]
好了是缓存的问题 多谢耐心指教
