### ISSUE TITLE
是否支持乡镇居委围栏扩展

### ISSUE THREAD

**Issue by SJshenjian** [yangyanggu/amap-district-cluster#4]
你好，目前想扩展乡镇、居委级别围栏，是否支持自定义扩展呢

**Comment by yangyanggu** [comment]
目前不支持，本质上这个是基于AMapUI的插件改造的，所以只能支持到跟它一样的级别，继续往下的话推荐自己实现，毕竟到乡镇级别的话，最高级也不会有多少多高

**Comment by SJshenjian** [comment]
好的
